### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by NikitaZhevnitskiy** [jeqo/zipkin-storage-kafka#15]
1. Improve tests code coverage
2. As an idea, replace Thread.sleep() with for example [awaitility](https://github.com/awaitility/awaitility)

**Comment by NikitaZhevnitskiy** [comment]
As an idea, replace Thread.sleep() with for example [awaitility](https://github.com/awaitility/awaitility)

**Comment by jeqo** [comment]
Fixed by #18
