### ISSUE TITLE
switch to zipkin's kafka test image?

### ISSUE THREAD

**Issue by adriancole** [jeqo/zipkin-storage-kafka#26]
https://github.com/jeqo/zipkin-storage-kafka/blob/master/docker-compose.yml I see a few docker images and not sure for example, the manager is required. Seems faster to start with the kafka-zk image we have? Similarly, it is possible to switch the dockerfile to the distroless approach from upstream? If nothing else, this will reduce the differences and allow for apples/apples comparison. We could still have a separate file like docker-compose-confluent for a more prod thing of kafka side of it.

**Comment by jeqo** [comment]
Fixed by #25
