### ISSUE TITLE
Mount storage libraries without uncompressing JAR

### ISSUE THREAD

**Issue by jeqo** [jeqo/zipkin-storage-kafka#28]
When building Docker image, setting classpath:

```
ENV MODULE_OPTS -Dloader.path='BOOT-INF/lib/kafka-module.jar,BOOT-INF/lib/kafka-module.jar!/lib' -Dspring.profiles.active=kafka
```

Is causing `ClassNotFound`.

Current workaround is unpacking JAR into classpath:

```
COPY autoconfigure/target/zipkin-autoconfigure-storage-kafka-${KAFKA_STORAGE_VERSION}-module.jar BOOT-INF/lib/kafka-module.jar
RUN unzip -o BOOT-INF/lib/kafka-module.jar lib/* -d BOOT-INF
```

**Comment by jeqo** [comment]
BTW this approach works fine on bash (host):

```
        STORAGE_TYPE=kafka \
	KAFKA_BOOTSTRAP_SERVERS=localhost:19092 \
	java \
	-Dloader.path='autoconfigure/target/zipkin-autoconfigure-storage-kafka-${VERSION}-module.jar,autoconfigure/target/zipkin-autoconfigure-storage-kafka-${VERSION}-module.jar!/lib' \
	-Dspring.profiles.active=kafka \
	-cp zipkin.jar \
	org.springframework.boot.loader.PropertiesLauncher
```

**Comment by adriancole** [comment]
so if I get you right.. in docker you cannot have compressed jars, but normaly you can.

maybe this has to do with that in docker we unpack zipkin.jar

**Comment by jeqo** [comment]
Right, trying to do this without unpacking zipkin jar, it works fine, check #30 

Then, I'm considering to keep zipkin jar and don't unzip it.

**Comment by adriancole** [comment]
unzipping was initially a way to help with incremental containers like cloudfoundry who tries to be smart about only moving necessary change. if you don't unzip, it is only an issue of layering of the base image which is unzipped.. I still think we should try to figure out why this is busted, but meanwhile making own image is fine!
